package e_comerenceApplication;


import static e_comerenceApplication.ProductScreen.readlastOrdersDataFile;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;

import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;







public class LoginScreen extends javax.swing.JFrame {

    
    
   
    User u1 ;
    static File userDataFile = new File("src/e_comerenceApplication/userData.txt");
    static ArrayList<String> userLogInArrayList = new ArrayList<>(); 
    static ArrayList<User> userList = new ArrayList<>();
    static ArrayList<String> favoriteProductArrayList = new ArrayList<>();
    static File favoriteProduct = new File ("src/e_comerenceApplication/favoriteProductsData.txt");
       
    public LoginScreen() {
        initComponents();
        parent.removeAll();
        parent.add(pnlLogin);
        parent.repaint();
        parent.revalidate();
        SwingUtilities.getWindowAncestor(parent).pack();
        this.setLocationRelativeTo(null);
       
        
    }
    public static void readUserDataFile(){
         
        try {
            Scanner scanner = new Scanner(userDataFile);
            while (scanner.hasNextLine()) {
                String line = scanner.nextLine();
                userLogInArrayList.add(line);
            }
        } catch (FileNotFoundException e) {
            throw new RuntimeException(e);
        }
    }
    
    public static void readFavoriteDataFile(){
        try {
            Scanner scanner = new Scanner(favoriteProduct);
            while (scanner.hasNextLine()) {
                String line = scanner.nextLine();
                favoriteProductArrayList.add(line);
            }
        } catch (FileNotFoundException e) {
            throw new RuntimeException(e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parent = new javax.swing.JPanel();
        pnlLogin = new javax.swing.JPanel();
        lblUsername1 = new javax.swing.JLabel();
        btnSignUp = new javax.swing.JButton();
        lblPassword = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnShowPassword = new javax.swing.JCheckBox();
        txtPassword = new javax.swing.JPasswordField();
        txtUsername = new javax.swing.JTextField();
        pnlSignUp = new javax.swing.JPanel();
        btnSignUpOk = new javax.swing.JButton();
        lblUsername2 = new javax.swing.JLabel();
        lblSurname = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtSignUpName = new javax.swing.JTextField();
        txtSignUpUsername = new javax.swing.JTextField();
        txtSignUpSurname = new javax.swing.JTextField();
        lblSurname5 = new javax.swing.JLabel();
        lblSurname6 = new javax.swing.JLabel();
        lblSurname7 = new javax.swing.JLabel();
        lblSurname8 = new javax.swing.JLabel();
        lblSurname9 = new javax.swing.JLabel();
        lblSurname10 = new javax.swing.JLabel();
        txtSignUpPhoneNum = new javax.swing.JTextField();
        txtSignUpPassword = new javax.swing.JTextField();
        txtSignUpBirthDate = new javax.swing.JTextField();
        txtSignUpEmail = new javax.swing.JTextField();
        txtSignUpHomeAddress = new javax.swing.JTextField();
        txtSignUpWorkAddress = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblUsername3 = new javax.swing.JLabel();
        lblUsername4 = new javax.swing.JLabel();
        lblUsername5 = new javax.swing.JLabel();
        lblUsername6 = new javax.swing.JLabel();
        txtCardNum = new javax.swing.JTextField();
        txtNameOnCard = new javax.swing.JTextField();
        txtCardSecurityCode = new javax.swing.JTextField();
        txtCardExpirationDate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("E-comerenceApplication Login");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        parent.setLayout(new java.awt.CardLayout());

        pnlLogin.setBackground(new java.awt.Color(255, 255, 255));
        pnlLogin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        pnlLogin.setForeground(new java.awt.Color(255, 255, 255));

        lblUsername1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUsername1.setForeground(new java.awt.Color(0, 0, 0));
        lblUsername1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsername1.setText("Username:");

        btnSignUp.setBackground(new java.awt.Color(255, 204, 0));
        btnSignUp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(0, 0, 0));
        btnSignUp.setText("SignUp");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(0, 0, 0));
        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPassword.setText("Password:");

        btnSubmit.setBackground(new java.awt.Color(255, 204, 0));
        btnSubmit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(0, 0, 0));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnShowPassword.setForeground(new java.awt.Color(0, 102, 255));
        btnShowPassword.setText("Show");
        btnShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowPasswordActionPerformed(evt);
            }
        });

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlLoginLayout.createSequentialGroup()
                                .addComponent(lblUsername1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSubmit))
                            .addGroup(pnlLoginLayout.createSequentialGroup()
                                .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnShowPassword))))
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSubmit))
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addComponent(lblUsername1)
                        .addGap(35, 35, 35)
                        .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPassword)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnShowPassword))))
                .addGap(18, 18, 18)
                .addComponent(btnSignUp)
                .addContainerGap())
        );

        parent.add(pnlLogin, "card2");

        pnlSignUp.setBackground(new java.awt.Color(255, 255, 255));
        pnlSignUp.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SignUp", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        pnlSignUp.setForeground(new java.awt.Color(255, 255, 255));
        pnlSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnSignUpOk.setBackground(new java.awt.Color(255, 204, 0));
        btnSignUpOk.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnSignUpOk.setForeground(new java.awt.Color(0, 0, 0));
        btnSignUpOk.setText("Continue");
        btnSignUpOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpOkActionPerformed(evt);
            }
        });

        lblUsername2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsername2.setForeground(new java.awt.Color(0, 0, 0));
        lblUsername2.setText("Name:");

        lblSurname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSurname.setForeground(new java.awt.Color(0, 0, 0));
        lblSurname.setText("Username:");

        lblName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 0, 0));
        lblName.setText("Surname:");

        txtSignUpName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSignUpName.setForeground(new java.awt.Color(0, 0, 0));

        txtSignUpUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSignUpUsername.setForeground(new java.awt.Color(0, 0, 0));

        txtSignUpSurname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSignUpSurname.setForeground(new java.awt.Color(0, 0, 0));

        lblSurname5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSurname5.setForeground(new java.awt.Color(0, 0, 0));
        lblSurname5.setText("Phone Num:");

        lblSurname6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSurname6.setForeground(new java.awt.Color(0, 0, 0));
        lblSurname6.setText("Password:");

        lblSurname7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSurname7.setForeground(new java.awt.Color(0, 0, 0));
        lblSurname7.setText("Birth Date:");

        lblSurname8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSurname8.setForeground(new java.awt.Color(0, 0, 0));
        lblSurname8.setText("E-mail:");

        lblSurname9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSurname9.setForeground(new java.awt.Color(0, 0, 0));
        lblSurname9.setText("Home Address:");

        lblSurname10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSurname10.setForeground(new java.awt.Color(0, 0, 0));
        lblSurname10.setText("Work Address:");

        txtSignUpPhoneNum.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSignUpPhoneNum.setForeground(new java.awt.Color(0, 0, 0));

        txtSignUpPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSignUpPassword.setForeground(new java.awt.Color(0, 0, 0));

        txtSignUpBirthDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSignUpBirthDate.setForeground(new java.awt.Color(0, 0, 0));

        txtSignUpEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSignUpEmail.setForeground(new java.awt.Color(0, 0, 0));

        txtSignUpHomeAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSignUpHomeAddress.setForeground(new java.awt.Color(0, 0, 0));

        txtSignUpWorkAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSignUpWorkAddress.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Credit Card");

        lblUsername3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsername3.setForeground(new java.awt.Color(0, 0, 0));
        lblUsername3.setText("Card Number:");

        lblUsername4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsername4.setForeground(new java.awt.Color(0, 0, 0));
        lblUsername4.setText("Name on Card:");

        lblUsername5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsername5.setForeground(new java.awt.Color(0, 0, 0));
        lblUsername5.setText("Security Code:");

        lblUsername6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsername6.setForeground(new java.awt.Color(0, 0, 0));
        lblUsername6.setText("Expiration Date:");

        txtCardNum.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCardNum.setForeground(new java.awt.Color(0, 0, 0));

        txtNameOnCard.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNameOnCard.setForeground(new java.awt.Color(0, 0, 0));

        txtCardSecurityCode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCardSecurityCode.setForeground(new java.awt.Color(0, 0, 0));

        txtCardExpirationDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCardExpirationDate.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlSignUpLayout = new javax.swing.GroupLayout(pnlSignUp);
        pnlSignUp.setLayout(pnlSignUpLayout);
        pnlSignUpLayout.setHorizontalGroup(
            pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSignUpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSignUpLayout.createSequentialGroup()
                        .addGroup(pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblSurname10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSurname9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSurname8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSurname7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSurname6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSurname5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUsername2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSurname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSignUpName, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(txtSignUpUsername, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSignUpSurname, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSignUpPhoneNum, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSignUpPassword)
                            .addComponent(txtSignUpBirthDate)
                            .addComponent(txtSignUpEmail)
                            .addComponent(txtSignUpHomeAddress)
                            .addComponent(txtSignUpWorkAddress)))
                    .addGroup(pnlSignUpLayout.createSequentialGroup()
                        .addGroup(pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblUsername3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUsername4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUsername5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsername6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCardNum, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                            .addComponent(txtNameOnCard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                            .addComponent(txtCardSecurityCode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                            .addComponent(txtCardExpirationDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(pnlSignUpLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(btnSignUpOk, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSignUpLayout.setVerticalGroup(
            pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSignUpLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSignUpName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsername2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtSignUpSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSurname)
                    .addComponent(txtSignUpUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSurname5)
                    .addComponent(txtSignUpPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSurname6)
                    .addComponent(txtSignUpPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSurname7)
                    .addComponent(txtSignUpBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSurname8)
                    .addComponent(txtSignUpEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSurname9)
                    .addComponent(txtSignUpHomeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSurname10)
                    .addComponent(txtSignUpWorkAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername3)
                    .addComponent(txtCardNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername4)
                    .addComponent(txtNameOnCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername5)
                    .addComponent(txtCardSecurityCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername6)
                    .addComponent(txtCardExpirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSignUpOk, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        parent.add(pnlSignUp, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnSignUpOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpOkActionPerformed
        boolean isEverythinkOk = txtSignUpBirthDate.getText().trim().isEmpty()&& txtSignUpEmail.getText().trim().isEmpty()&& txtSignUpHomeAddress.getText().trim().isEmpty()
                && txtSignUpName.getText().trim().isEmpty() && txtSignUpPassword.getText().trim().isEmpty() && txtSignUpPhoneNum.getText().trim().isEmpty() &&
                txtSignUpSurname.getText().trim().isEmpty() && txtSignUpUsername.getText().trim().isEmpty() && txtSignUpWorkAddress.getText().trim().isEmpty()&&
                txtCardExpirationDate.getText().trim().isEmpty() && txtCardNum.getText().trim().isEmpty()&&txtCardSecurityCode.getText().trim().isEmpty()
                && txtNameOnCard.getText().trim().isEmpty();
       
        if(!isEverythinkOk){
         
        String userName = txtSignUpUsername.getText();
        String password = txtSignUpPassword.getText();
        String name     = txtSignUpName.getText();
        String surname  = txtSignUpSurname.getText();
        String phoneNum = txtSignUpPhoneNum.getText();
        String birthDate = txtSignUpBirthDate.getText();
        String email = txtSignUpBirthDate.getText();
        String homeAddress = txtSignUpHomeAddress.getText(); 
        String workAddress = txtSignUpWorkAddress.getText();
        String cardNumber =  txtCardNum.getText();
        String nameOnCard = txtNameOnCard.getText();
        String cvc = txtCardSecurityCode.getText();
        String expirationDate = txtCardExpirationDate.getText();
        User u1 = new User(name,surname,userName,phoneNum,password,birthDate,email,homeAddress,workAddress,new CreditCard(cardNumber,nameOnCard,cvc,expirationDate));
        userList.add(u1);
        try {
            BufferedWriter writer = new BufferedWriter(new FileWriter(userDataFile,true));
            writer.write(userName+","+password+","+name+","+surname+","+phoneNum+","+birthDate+","+email+","+
                    homeAddress+","+workAddress+","+cardNumber+","+nameOnCard+","+cvc+","+expirationDate);
            writer.newLine();
            writer.close();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
         JOptionPane.showMessageDialog(this, "Sign successfully!", "Info", JOptionPane.INFORMATION_MESSAGE);
   
        parent.removeAll();
        parent.add(pnlLogin);
        parent.repaint();
        parent.revalidate();
        SwingUtilities.getWindowAncestor(parent).pack();
        this.setLocationRelativeTo(null);
        }else{
            JOptionPane.showMessageDialog(null, "Please fill the all blanks complately!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnSignUpOkActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowPasswordActionPerformed
        if (txtPassword.getEchoChar() == (char) 0) {
            txtPassword.setEchoChar('*');
            btnShowPassword.setText("Show");
        }
        else {
            txtPassword.setEchoChar((char) 0);
            btnShowPassword.setText("Hide");
        }
    }//GEN-LAST:event_btnShowPasswordActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        boolean logInCheck= false ;
        String entryUserName = txtUsername.getText();
        String entryPassword = txtPassword.getText();

        for (User user : userList){
            String uName = user.getUserName();
            String uPassword = user.getPassword();
            if(uName.equals(entryUserName) && uPassword.equals(entryPassword)){
                logInCheck = true;
                u1=user;
                break;
               
            }
        }

        if(logInCheck){
            new ProductScreen(u1).setVisible(true);
            this.setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(null, "Username or Password Incorrect!", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        parent.removeAll();
        parent.add(pnlSignUp);
        parent.repaint();
        parent.revalidate();
        SwingUtilities.getWindowAncestor(parent).pack();
        this.setLocationRelativeTo(null);

    }//GEN-LAST:event_btnSignUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen().setVisible(true);
                try {
                    readUserDataFile();
                } catch (Exception e){
                    System.out.println("Porgram basindaki readUserDataFile methodu hata aldi.");  
                }
                 try {
                    readlastOrdersDataFile();
                } catch (Exception e){
                    System.out.println("Porgram basindaki readlastOrdersDataFile methodu hata aldi.");  
                }
                  try {
                      readFavoriteDataFile();
                } catch (Exception e){
                    System.out.println("Porgram basindaki readFavoriteDataFile methodu hata aldi.");  
                }
                
                for(String userData : userLogInArrayList){
                    String[] finalUserData = userData.split(",");
                    if (finalUserData.length==13) {
                     String userName=finalUserData[0] ;
                     String password =finalUserData[1]; 
                     String name   =finalUserData[2]  ;
                     String surname =finalUserData[3] ; 
                     String phoneNum=finalUserData[4] ; 
                     String birthDate=finalUserData[5]; 
                     String email =finalUserData[6]   ;
                     String homeAddress =finalUserData[7];
                     String workAddress =finalUserData[8];
                     String cardNumber=finalUserData[9];
                     String nameOnCard =finalUserData[10];
                     String cvc=finalUserData[11]     ;
                     String expirationDate =finalUserData[12];
                     User u1 =new User(name,surname,userName,phoneNum,password,birthDate,email,homeAddress,
                             workAddress,new CreditCard(cardNumber,nameOnCard,cvc,expirationDate));
                     userList.add(u1);
                    
                     
                     
                     
                    }
                     
                
                
                }
                
                
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox btnShowPassword;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JButton btnSignUpOk;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSurname;
    private javax.swing.JLabel lblSurname10;
    private javax.swing.JLabel lblSurname5;
    private javax.swing.JLabel lblSurname6;
    private javax.swing.JLabel lblSurname7;
    private javax.swing.JLabel lblSurname8;
    private javax.swing.JLabel lblSurname9;
    private javax.swing.JLabel lblUsername1;
    private javax.swing.JLabel lblUsername2;
    private javax.swing.JLabel lblUsername3;
    private javax.swing.JLabel lblUsername4;
    private javax.swing.JLabel lblUsername5;
    private javax.swing.JLabel lblUsername6;
    private javax.swing.JPanel parent;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlSignUp;
    private javax.swing.JTextField txtCardExpirationDate;
    private javax.swing.JTextField txtCardNum;
    private javax.swing.JTextField txtCardSecurityCode;
    private javax.swing.JTextField txtNameOnCard;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtSignUpBirthDate;
    private javax.swing.JTextField txtSignUpEmail;
    private javax.swing.JTextField txtSignUpHomeAddress;
    private javax.swing.JTextField txtSignUpName;
    private javax.swing.JTextField txtSignUpPassword;
    private javax.swing.JTextField txtSignUpPhoneNum;
    private javax.swing.JTextField txtSignUpSurname;
    private javax.swing.JTextField txtSignUpUsername;
    private javax.swing.JTextField txtSignUpWorkAddress;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
