package e_comerenceApplication;





import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;


//Kullanicilar kalici olarak kayit edilecek yeni kullanicilar da dahil               √√
//Kullanici spepte ekledigi urun uyuglamaya gir cik yaptiginda hala sepette kalmali  xx
//Kullanicinin Favladigi urunler kalici olmali                                       √√     
//Kullanicinin Eski siparisleri kalici hale getirilmeli                              √√                                
//Kullnaicinin kredi kartlari da kalici olarak kaydedilecek                          √√            





public class ProductScreen extends javax.swing.JFrame {

    /**
     * Creates new form ProductScreen
     */
    Product p1 = new Product("Introduction to Java Programming","Blue","Book",15,2.5,"Book for start to learn java programming.","999 Tl");
    Product p2 = new Product("RTX 5090","Black","Tech.",10,0.8,"Graphics Processing Unit (GPU)","59499 Tl");
    Product p3 = new Product("Chess Set","White and Black","Hoby",8,1,"Chess set for hobby","49,99 Tl");
    Product p4 = new Product("Fenerbahce Jersey","Yellow and Navy Blue","Spor",3,0.3,"2024-2025 Fenerbahce home jersey","4500 Tl");
    static File orders = new File("src/e_comerenceApplication/lastOrdersData.txt");
    static File favoriteProduct = new File ("src/e_comerenceApplication/favoriteProductsData.txt");
    private boolean favlandı;
    private User user;
    private String userName;
    private Product visitedProduct;
    DefaultListModel favList;
    DefaultListModel cartList;
    DefaultListModel lastOrders;
    static ArrayList<String> lastOrdersArrayList;
    static ArrayList<String> favoriteProductArrayList;
    ArrayList<Product> favoriteProducts = new ArrayList<>();
    
  
    public ProductScreen(User user) {
        initComponents();
        favList = new DefaultListModel();
        lstFav.setModel(favList);
        cartList = new DefaultListModel();
        lastOrders = new DefaultListModel();
        lstCart.setModel(cartList);
        lstLastOrders.setModel(lastOrders);
        this.user = user;
        this.userName = user.getUserName();
        this.setLocationRelativeTo(null);
        lblUsername.setText(userName);
        lstProducts.addItem(p1.getProductName());
        lstProducts.addItem(p2.getProductName());
        lstProducts.addItem(p3.getProductName());
        lstProducts.addItem(p4.getProductName());
        
        
        
    }
    
    public static void readlastOrdersDataFile(){
      lastOrdersArrayList=new ArrayList<>();
        try {
            Scanner scanner = new Scanner(orders);
            while (scanner.hasNextLine()) {
                String line = scanner.nextLine();
                lastOrdersArrayList.add(line);
               
            }
        } catch (FileNotFoundException e) {
            throw new RuntimeException(e);
        }  
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        parent = new javax.swing.JPanel();
        pnlProducts = new javax.swing.JPanel();
        lstProducts = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblProductName = new javax.swing.JLabel();
        lblProductColor = new javax.swing.JLabel();
        lblProductCategory = new javax.swing.JLabel();
        lblProductStock = new javax.swing.JLabel();
        lblProductWeight = new javax.swing.JLabel();
        lblProductInfo = new javax.swing.JLabel();
        btnMinus = new javax.swing.JButton();
        btnPlus = new javax.swing.JButton();
        lblCount = new javax.swing.JLabel();
        btnAddCart = new javax.swing.JButton();
        btnFav = new javax.swing.JButton();
        btnMyCart = new javax.swing.JButton();
        btnFavList = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblImg = new javax.swing.JLabel();
        btnOrders = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        pnlFavorites = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstFav = new javax.swing.JList<>();
        btnBack = new javax.swing.JButton();
        pnlCart = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstCart = new javax.swing.JList<>();
        btnOrder = new javax.swing.JButton();
        btnBack2 = new javax.swing.JButton();
        pnlOrder = new javax.swing.JPanel();
        lstCreditCards = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        btnFinishOrder = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        lblUsername3 = new javax.swing.JLabel();
        lblUsername4 = new javax.swing.JLabel();
        lblUsername5 = new javax.swing.JLabel();
        lblUsername6 = new javax.swing.JLabel();
        txtCardExpirationDate = new javax.swing.JTextField();
        txtCardSecurityCode = new javax.swing.JTextField();
        txtCardUsername = new javax.swing.JTextField();
        txtCardNum = new javax.swing.JTextField();
        pnlOrders = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        lstLastOrders = new javax.swing.JList<>();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("E-comerenceApplication");

        parent.setLayout(new java.awt.CardLayout());

        pnlProducts.setBackground(new java.awt.Color(255, 255, 255));

        lstProducts.setBackground(new java.awt.Color(204, 204, 204));
        lstProducts.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lstProducts.setForeground(new java.awt.Color(0, 0, 0));
        lstProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lstProductsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Products:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Name:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Color:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Category:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Stock Info:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Weight:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Description Info:");

        lblProductName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblProductName.setForeground(new java.awt.Color(0, 0, 0));
        lblProductName.setText("name");

        lblProductColor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblProductColor.setForeground(new java.awt.Color(0, 0, 0));
        lblProductColor.setText("color");

        lblProductCategory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblProductCategory.setForeground(new java.awt.Color(0, 0, 0));
        lblProductCategory.setText("category");

        lblProductStock.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblProductStock.setForeground(new java.awt.Color(0, 0, 0));
        lblProductStock.setText("916516");

        lblProductWeight.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblProductWeight.setForeground(new java.awt.Color(0, 0, 0));
        lblProductWeight.setText("weight");

        lblProductInfo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblProductInfo.setForeground(new java.awt.Color(0, 0, 0));
        lblProductInfo.setText("info");

        btnMinus.setBackground(new java.awt.Color(204, 153, 0));
        btnMinus.setForeground(new java.awt.Color(0, 0, 0));
        btnMinus.setText("-");
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusActionPerformed(evt);
            }
        });

        btnPlus.setBackground(new java.awt.Color(204, 153, 0));
        btnPlus.setForeground(new java.awt.Color(0, 0, 0));
        btnPlus.setText("+");
        btnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusActionPerformed(evt);
            }
        });

        lblCount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCount.setForeground(new java.awt.Color(0, 0, 0));
        lblCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCount.setText("1");

        btnAddCart.setBackground(new java.awt.Color(255, 204, 0));
        btnAddCart.setForeground(new java.awt.Color(0, 0, 0));
        btnAddCart.setText("Add to Cart");
        btnAddCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCartActionPerformed(evt);
            }
        });

        btnFav.setBackground(new java.awt.Color(255, 255, 255));
        btnFav.setForeground(new java.awt.Color(153, 153, 153));
        btnFav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/heart.png"))); // NOI18N
        btnFav.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnFav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFavActionPerformed(evt);
            }
        });

        btnMyCart.setBackground(new java.awt.Color(204, 204, 204));
        btnMyCart.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnMyCart.setForeground(new java.awt.Color(0, 0, 0));
        btnMyCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cart.png"))); // NOI18N
        btnMyCart.setText("   Cart");
        btnMyCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyCartActionPerformed(evt);
            }
        });

        btnFavList.setBackground(new java.awt.Color(204, 204, 204));
        btnFavList.setForeground(new java.awt.Color(0, 0, 0));
        btnFavList.setText("Favorites");
        btnFavList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFavListActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("User:");

        lblUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(0, 0, 0));
        lblUsername.setText("user1");

        lblImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/java.png"))); // NOI18N

        btnOrders.setBackground(new java.awt.Color(204, 204, 204));
        btnOrders.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnOrders.setForeground(new java.awt.Color(0, 0, 0));
        btnOrders.setText("Orders");
        btnOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdersActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Apple Braille", 1, 17)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText(" Price :");

        javax.swing.GroupLayout pnlProductsLayout = new javax.swing.GroupLayout(pnlProducts);
        pnlProducts.setLayout(pnlProductsLayout);
        pnlProductsLayout.setHorizontalGroup(
            pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProductsLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProductsLayout.createSequentialGroup()
                        .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlProductsLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lstProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnFav, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlProductsLayout.createSequentialGroup()
                                .addComponent(lblImg, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlProductsLayout.createSequentialGroup()
                                        .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lblProductWeight, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblProductStock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblProductCategory, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblProductColor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblProductName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblProductInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblPrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(pnlProductsLayout.createSequentialGroup()
                                        .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(btnAddCart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(pnlProductsLayout.createSequentialGroup()
                                                .addComponent(btnMinus)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblCount, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnPlus)))
                                        .addGap(24, 24, 24)))))
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProductsLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFavList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMyCart)
                        .addContainerGap())))
        );
        pnlProductsLayout.setVerticalGroup(
            pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(lblUsername))
                    .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnMyCart)
                        .addComponent(btnOrders)
                        .addComponent(btnFavList)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProductsLayout.createSequentialGroup()
                        .addComponent(lstProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlProductsLayout.createSequentialGroup()
                                .addGap(202, 202, 202)
                                .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnMinus)
                                    .addComponent(lblCount, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPlus)))
                            .addGroup(pnlProductsLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(38, 38, 38))))
                    .addGroup(pnlProductsLayout.createSequentialGroup()
                        .addComponent(btnFav, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblProductName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblProductColor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblProductCategory))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProductStock, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(lblProductWeight))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblProductInfo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlProductsLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddCart, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        parent.add(pnlProducts, "card2");

        pnlFavorites.setBackground(new java.awt.Color(255, 255, 255));
        pnlFavorites.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Favorites", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        lstFav.setBackground(new java.awt.Color(204, 204, 204));
        lstFav.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lstFav.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstFav);

        btnBack.setBackground(new java.awt.Color(255, 204, 0));
        btnBack.setForeground(new java.awt.Color(0, 0, 0));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFavoritesLayout = new javax.swing.GroupLayout(pnlFavorites);
        pnlFavorites.setLayout(pnlFavoritesLayout);
        pnlFavoritesLayout.setHorizontalGroup(
            pnlFavoritesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFavoritesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFavoritesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnlFavoritesLayout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlFavoritesLayout.setVerticalGroup(
            pnlFavoritesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFavoritesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBack)
                .addGap(25, 25, 25))
        );

        parent.add(pnlFavorites, "card3");

        pnlCart.setBackground(new java.awt.Color(255, 255, 255));
        pnlCart.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "My Cart", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        lstCart.setBackground(new java.awt.Color(255, 255, 255));
        lstCart.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lstCart.setForeground(new java.awt.Color(0, 0, 0));
        lstCart.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(lstCart);

        btnOrder.setBackground(new java.awt.Color(255, 204, 0));
        btnOrder.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnOrder.setForeground(new java.awt.Color(0, 0, 0));
        btnOrder.setText("Order");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        btnBack2.setBackground(new java.awt.Color(204, 204, 204));
        btnBack2.setForeground(new java.awt.Color(0, 0, 0));
        btnBack2.setText("Back");
        btnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCartLayout = new javax.swing.GroupLayout(pnlCart);
        pnlCart.setLayout(pnlCartLayout);
        pnlCartLayout.setHorizontalGroup(
            pnlCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCartLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlCartLayout.createSequentialGroup()
                        .addComponent(btnBack2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pnlCartLayout.setVerticalGroup(
            pnlCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCartLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOrder)
                    .addComponent(btnBack2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        parent.add(pnlCart, "card4");

        pnlOrder.setBackground(new java.awt.Color(255, 255, 255));
        pnlOrder.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Order", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        lstCreditCards.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lstCreditCardsActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Credit Cards:");

        btnFinishOrder.setBackground(new java.awt.Color(255, 204, 0));
        btnFinishOrder.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        btnFinishOrder.setForeground(new java.awt.Color(0, 0, 0));
        btnFinishOrder.setText("Finish Order");
        btnFinishOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinishOrderActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Use Another Card :");

        lblUsername3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsername3.setForeground(new java.awt.Color(0, 0, 0));
        lblUsername3.setText("Card Number:");

        lblUsername4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsername4.setForeground(new java.awt.Color(0, 0, 0));
        lblUsername4.setText("Username:");

        lblUsername5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsername5.setForeground(new java.awt.Color(0, 0, 0));
        lblUsername5.setText("Security Code:");

        lblUsername6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsername6.setForeground(new java.awt.Color(0, 0, 0));
        lblUsername6.setText("Expiration Date:");

        txtCardExpirationDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCardExpirationDate.setForeground(new java.awt.Color(0, 0, 0));

        txtCardSecurityCode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCardSecurityCode.setForeground(new java.awt.Color(0, 0, 0));

        txtCardUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCardUsername.setForeground(new java.awt.Color(0, 0, 0));
        txtCardUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCardUsernameActionPerformed(evt);
            }
        });

        txtCardNum.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCardNum.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlOrderLayout = new javax.swing.GroupLayout(pnlOrder);
        pnlOrder.setLayout(pnlOrderLayout);
        pnlOrderLayout.setHorizontalGroup(
            pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrderLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlOrderLayout.createSequentialGroup()
                        .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlOrderLayout.createSequentialGroup()
                                .addComponent(lstCreditCards, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btnFinishOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOrderLayout.createSequentialGroup()
                        .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlOrderLayout.createSequentialGroup()
                                .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblUsername3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblUsername4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblUsername5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblUsername6, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCardNum, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                                    .addComponent(txtCardUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                                    .addComponent(txtCardSecurityCode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                                    .addComponent(txtCardExpirationDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)))
                            .addGroup(pnlOrderLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAdd)))
                        .addGap(41, 41, 41))))
        );
        pnlOrderLayout.setVerticalGroup(
            pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrderLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lstCreditCards, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFinishOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername3)
                    .addComponent(txtCardNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername4)
                    .addComponent(txtCardUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername5)
                    .addComponent(txtCardSecurityCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername6)
                    .addComponent(txtCardExpirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        parent.add(pnlOrder, "card5");

        pnlOrders.setBackground(new java.awt.Color(255, 255, 255));
        pnlOrders.setPreferredSize(new java.awt.Dimension(665, 432));

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("ORDERS");

        jButton1.setBackground(new java.awt.Color(255, 204, 0));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lstLastOrders.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(lstLastOrders);

        javax.swing.GroupLayout pnlOrdersLayout = new javax.swing.GroupLayout(pnlOrders);
        pnlOrders.setLayout(pnlOrdersLayout);
        pnlOrdersLayout.setHorizontalGroup(
            pnlOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrdersLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlOrdersLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlOrdersLayout.setVerticalGroup(
            pnlOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrdersLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(16, 16, 16))
        );

        parent.add(pnlOrders, "card6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parent, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        parent.removeAll();
        parent.add(pnlProducts);
        parent.repaint();
        parent.revalidate();
        SwingUtilities.getWindowAncestor(parent).pack();
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnFavListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFavListActionPerformed
        favList.clear();
       
        parent.removeAll();
        parent.add(pnlFavorites);
        parent.repaint();
        parent.revalidate();
        SwingUtilities.getWindowAncestor(parent).pack();
        this.setLocationRelativeTo(null);
        for(int i = 0;i<user.getFavoriteProductList().size();i++){
            favList.addElement(user.getFavoriteProductList().get(i).getProductName());
        }
        
       
              
        
        
    }//GEN-LAST:event_btnFavListActionPerformed

    private void btnFavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFavActionPerformed
        if(!favlandı){
            btnFav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/heart_filled.png")));
            favlandı = true;
            user.addToFavoriteProductList(visitedProduct);
             
            try {
                BufferedWriter writer = new BufferedWriter(new FileWriter(favoriteProduct,true));
                writer.write(user.getUserName()+","+visitedProduct.getProductName());
                writer.newLine();
                writer.close();
            } catch (IOException ex) {
                Logger.getLogger(ProductScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            
            
            
             
            
            
        }
        else {
            btnFav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/heart.png")));
            favlandı = false;
            user.removeToFavoriteProductList(visitedProduct);
        }

    }//GEN-LAST:event_btnFavActionPerformed

    private void btnAddCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCartActionPerformed
 
        if(visitedProduct.getProductStockİnformation()>0){  //check the stock info
            
            if(user.getCartList().contains(visitedProduct)){
               
                user.getCartList().remove(visitedProduct);
                user.addToCart(visitedProduct,Integer.parseInt(lblCount.getText()));
                lblProductStock.setText(visitedProduct.getProductStockİnformation()+"");
                lblCount.setText(1+"");
                 
          
            }
            
            else{
                user.addToCart(visitedProduct,Integer.parseInt(lblCount.getText()));
                lblProductStock.setText(visitedProduct.getProductStockİnformation()+"");
                lblCount.setText(1+"");
            
            }
            
            if(visitedProduct.getProductStockİnformation()==0){
            lblCount.setText(0+"");
            }
            
        }
        
        else{
            JOptionPane.showMessageDialog(null, "Out of stock!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddCartActionPerformed

    private void btnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusActionPerformed
        if(!lblCount.getText().equals(lblProductStock.getText())){
            lblCount.setText(Integer.parseInt(lblCount.getText())+1+"");
        }
    }//GEN-LAST:event_btnPlusActionPerformed

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusActionPerformed
        if(!lblCount.getText().equals(1+"")&&!lblCount.getText().equals(0+"")){
            lblCount.setText(Integer.parseInt(lblCount.getText())-1+"");
        }
        
    }//GEN-LAST:event_btnMinusActionPerformed

    private void lstProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lstProductsActionPerformed
        if(lstProducts.getSelectedItem().equals(p1.getProductName())){
            visitedProduct=p1;
            lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/java.png")));
        }
        else if(lstProducts.getSelectedItem().equals(p2.getProductName())){
            visitedProduct=p2;
            lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rtx.png")));
        }
        else if(lstProducts.getSelectedItem().equals(p3.getProductName())){
            visitedProduct=p3;
            lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/chess.png")));
        }
        else if(lstProducts.getSelectedItem().equals(p4.getProductName())){
            visitedProduct=p4;
            lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fenerbahce.png")));
        }
        lblProductName.setText(visitedProduct.getProductName());
        lblProductColor.setText(visitedProduct.getProductColor());
        lblProductCategory.setText(visitedProduct.getProductCategory());
        lblProductStock.setText(visitedProduct.getProductStockİnformation()+"");
        lblProductWeight.setText(visitedProduct.getWeight()+" kg");
        lblProductInfo.setText(visitedProduct.getDescriptionProduct());
        lblCount.setText(1+"");
        lblPrice.setText(visitedProduct.getPrice());
        

        if(user.getFavoriteProductList().contains(visitedProduct)){
            btnFav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/heart_filled.png")));
            favlandı = true;
        }
        else {
            btnFav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/heart.png")));
            favlandı = false;
        }
    }//GEN-LAST:event_lstProductsActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        parent.removeAll();
        parent.add(pnlOrder);
        parent.repaint();
        parent.revalidate();
        
        SwingUtilities.getWindowAncestor(parent).pack();
        this.setLocationRelativeTo(null);
        
        for(CreditCard x : user.getCardList()){
            String cardNumber =x.getCreditCardNumber();
            lstCreditCards.addItem(cardNumber);
        }
    }//GEN-LAST:event_btnOrderActionPerformed

    private void btnMyCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyCartActionPerformed
        
        parent.removeAll();
        parent.add(pnlCart);
        parent.repaint();
        parent.revalidate();
        SwingUtilities.getWindowAncestor(parent).pack();
        this.setLocationRelativeTo(null);
        cartList.clear();
        for(int i = 0;i<user.getCartList().size();i++){
            cartList.addElement((user.getCartList().get(i).getProductStartStock()-user.getCartList().get(i).getProductStockİnformation())+" pieces "+user.getCartList().get(i).getProductName());
        }
    }//GEN-LAST:event_btnMyCartActionPerformed

    private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack2ActionPerformed
        parent.removeAll();
        parent.add(pnlProducts);
        parent.repaint();
        parent.revalidate();
        SwingUtilities.getWindowAncestor(parent).pack();
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnBack2ActionPerformed

    private void lstCreditCardsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lstCreditCardsActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_lstCreditCardsActionPerformed

    private void btnFinishOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishOrderActionPerformed
       
        // Kullanicinin Satin aldigi urunleri lastOrdarsData.txt dosyasina yazar
         for (int i = 0; i < user.getCartList().size() ; i++) {
             try {
                lastOrders.clear();
                BufferedWriter writer = new BufferedWriter(new FileWriter(orders,true));
                writer.write(user.getUserName()+","+user.getCartList().get(i).getProductName());
                writer.newLine();
                writer.close();
            } catch (IOException ex) {
                Logger.getLogger(ProductScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
             
             
             
             
             
        }
         
        for(int i = 0;i<user.getCartList().size();i++){
            Order order = new Order(user,user.getCartList().get(i),user.getCreditCard());
            String productName = user.getCartList().get(i).getProductName();
           
         
            order.FinishOrder();
        }
       
       
        JOptionPane.showMessageDialog(this, "Purchase completed successfully!", "Info", JOptionPane.INFORMATION_MESSAGE);
        parent.removeAll();
        parent.add(pnlProducts);
        parent.repaint();
        parent.revalidate();
        SwingUtilities.getWindowAncestor(parent).pack();
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnFinishOrderActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

    String creditCardNumber = txtCardNum.getText();
    String nameOnCard = txtCardUsername.getText();
    String cardExpirationDate = txtCardExpirationDate.getText();
    String cvc = txtCardSecurityCode.getText();
    
    user.addCreditCardOnCardList(new CreditCard(creditCardNumber,nameOnCard,cvc,cardExpirationDate));
    
    for(CreditCard x : user.getCardList()){
            String cardNumber =x.getCreditCardNumber();
           
            for(int i = 0 ; i < lstCreditCards.getItemCount() ; i++){
                if(!lstCreditCards.getItemAt(i).equals(cardNumber)){
                    lstCreditCards.addItem(cardNumber);
                }
            }
        }
    
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdersActionPerformed
        // TODO add your handling code here:
        
        for(String x : lastOrdersArrayList){
            if(user.getUserName().equals(x.substring(0, x.indexOf(",")))){
               lastOrders.addElement(x.substring(x.indexOf(",")+1));
            }
        }
        parent.removeAll();
        parent.add(pnlOrders);
        parent.repaint();
        parent.revalidate();
        SwingUtilities.getWindowAncestor(parent).pack();
        this.setLocationRelativeTo(null);
        cartList.clear();
    }//GEN-LAST:event_btnOrdersActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        parent.removeAll();
        parent.add(pnlProducts);
        parent.repaint();
        parent.revalidate();
        SwingUtilities.getWindowAncestor(parent).pack();
        this.setLocationRelativeTo(null);
        cartList.clear();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCardUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCardUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCardUsernameActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    readlastOrdersDataFile();
                } catch (Exception e){
                    System.out.println("Porgram basindaki readlastOrdersDataFile methodu hata aldi.");  
                }
                try{
                    LoginScreen.readFavoriteDataFile();
                }catch (Exception e){
                    System.out.println("Porgram basindaki readFavo methodu hata aldi.");
                }
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddCart;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack2;
    private javax.swing.JButton btnFav;
    private javax.swing.JButton btnFavList;
    private javax.swing.JButton btnFinishOrder;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnMyCart;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnOrders;
    private javax.swing.JButton btnPlus;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblCount;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblProductCategory;
    private javax.swing.JLabel lblProductColor;
    private javax.swing.JLabel lblProductInfo;
    private javax.swing.JLabel lblProductName;
    private javax.swing.JLabel lblProductStock;
    private javax.swing.JLabel lblProductWeight;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblUsername3;
    private javax.swing.JLabel lblUsername4;
    private javax.swing.JLabel lblUsername5;
    private javax.swing.JLabel lblUsername6;
    private javax.swing.JList<String> lstCart;
    private javax.swing.JComboBox<String> lstCreditCards;
    private javax.swing.JList<String> lstFav;
    private javax.swing.JList<String> lstLastOrders;
    private javax.swing.JComboBox<String> lstProducts;
    private javax.swing.JPanel parent;
    private javax.swing.JPanel pnlCart;
    private javax.swing.JPanel pnlFavorites;
    private javax.swing.JPanel pnlOrder;
    private javax.swing.JPanel pnlOrders;
    private javax.swing.JPanel pnlProducts;
    private javax.swing.JTextField txtCardExpirationDate;
    private javax.swing.JTextField txtCardNum;
    private javax.swing.JTextField txtCardSecurityCode;
    private javax.swing.JTextField txtCardUsername;
    // End of variables declaration//GEN-END:variables
}
